/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebabayesianas;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Edgar
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public String yy="";
    public interfaz() {
        initComponents();
        //nodos.show(false);
        //campoResul.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nodos = new javax.swing.JTable();
        btn2 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        informacion = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        informacion2 = new javax.swing.JTextArea();
        labelRound1 = new org.edisoncor.gui.label.LabelRound();
        labelRound2 = new org.edisoncor.gui.label.LabelRound();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoResul = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(850, 730));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(820, 710));
        jPanel2.setPreferredSize(new java.awt.Dimension(820, 710));
        jPanel2.setLayout(null);

        nodos.setBackground(new java.awt.Color(0, 153, 153));
        nodos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "NODOS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        nodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nodosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nodos);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(50, 112, 168, 340);

        btn2.setBackground(new java.awt.Color(0, 51, 51));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn2.setText("Cargar Archivo");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);
        btn2.setBounds(600, 60, 140, 36);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre);
        txtNombre.setBounds(250, 60, 310, 30);

        informacion.setBackground(new java.awt.Color(0, 102, 255));
        informacion.setColumns(20);
        informacion.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        informacion.setRows(5);
        jScrollPane3.setViewportView(informacion);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(270, 140, 466, 96);

        informacion2.setBackground(new java.awt.Color(0, 102, 255));
        informacion2.setColumns(20);
        informacion2.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        informacion2.setRows(5);
        jScrollPane4.setViewportView(informacion2);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(270, 330, 466, 114);

        labelRound1.setBackground(new java.awt.Color(153, 204, 255));
        labelRound1.setText("Descripción Nodos");
        jPanel2.add(labelRound1);
        labelRound1.setBounds(270, 300, 217, 29);

        labelRound2.setBackground(new java.awt.Color(153, 204, 255));
        labelRound2.setText("Valores del Nodo");
        jPanel2.add(labelRound2);
        labelRound2.setBounds(270, 110, 229, 29);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("DESCRIPCIÓN DE LA RED BAYESIANA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 10, 460, 35);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción de la Red", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        campoResul.setBackground(new java.awt.Color(204, 204, 204));
        campoResul.setColumns(20);
        campoResul.setFont(new java.awt.Font("BatangChe", 0, 12)); // NOI18N
        campoResul.setForeground(new java.awt.Color(255, 255, 255));
        campoResul.setRows(5);
        jScrollPane2.setViewportView(campoResul);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 490, 750, 200);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 820, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        //Mostrar la ventana para abrir archivo y recoger la respuesta
        //En el parámetro del showOpenDialog se indica la ventana
        //  al que estará asociado. Con el valor this se asocia a la
        //  ventana que la abre.
        int respuesta = fc.showOpenDialog(this);
        //Comprobar si se ha pulsado Aceptar
        if (respuesta == JFileChooser.APPROVE_OPTION){
            //Crear un objeto File con el archivo elegido
                File archivoElegido = fc.getSelectedFile();
            //Mostrar el nombre del archvivo en un campo de texto
            txtNombre.setText("");
            txtNombre.setText(archivoElegido.getName());
            txtNombre.setEditable(false);
            String y=archivoElegido.getAbsolutePath();///obtengo la ruta del archivo elegido para enviarlo como parametro
            yy=y;
            new PruebaBayesianas();
            PruebaBayesianas a = new PruebaBayesianas();
            for(int i=0; i<25; i++){
                nodos.setValueAt("", i, 0);
            }
            int i = 0;
            nodos.show(true);
            campoResul.setVisible(true);
            campoResul.setText("");
            informacion.setText("");
            informacion2.setText("");
            for (modelo x : a.obtenerNodos(y)) {
                nodos.setValueAt(x.getNombre(), i, 0);
                campoResul.setText(String.valueOf(x.getResul()));
                i++;
                
            }
            campoResul.setEditable(false);
           
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void nodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nodosMouseClicked

        PruebaBayesianas a = new PruebaBayesianas();
        informacion.setText(String.valueOf(a.informacion(String.valueOf(nodos.getValueAt(nodos.getSelectedRow(),nodos.getSelectedColumn())), yy)));
        informacion2.setText(String.valueOf(a.devInf(String.valueOf(nodos.getValueAt(nodos.getSelectedRow(),nodos.getSelectedColumn())), yy)).concat("\nRelevancia: ").concat(String.valueOf(a.relevancia(String.valueOf(nodos.getValueAt(nodos.getSelectedRow(),nodos.getSelectedColumn())), yy))));
       
        
        
        informacion.setEditable(false);
        informacion2.setEditable(false);
    }//GEN-LAST:event_nodosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2;
    private javax.swing.JTextArea campoResul;
    private javax.swing.JTextArea informacion;
    private javax.swing.JTextArea informacion2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private org.edisoncor.gui.label.LabelRound labelRound1;
    private org.edisoncor.gui.label.LabelRound labelRound2;
    private javax.swing.JTable nodos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
